# Generated by Django 4.2.4 on 2023-09-04 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_shop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_shop',
        ),
    ]
