# Generated by Django 4.2.4 on 2023-09-04 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_remove_tbl_shop_district_remove_tbl_shop_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=45)),
                ('proof', models.FileField(upload_to='Shopproof/')),
                ('photo', models.FileField(upload_to='Shopphoto/')),
                ('password', models.CharField(max_length=40)),
                ('conpassword', models.CharField(max_length=40)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=55)),
                ('gender', models.CharField(max_length=45)),
                ('photo', models.FileField(upload_to='Userphoto/')),
                ('password', models.CharField(max_length=45)),
                ('conpassword', models.CharField(max_length=50)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
