# Generated by Django 4.2.4 on 2023-09-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_shop_tbl_newuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_shop',
            name='place',
        ),
        migrations.DeleteModel(
            name='tbl_newuser',
        ),
        migrations.DeleteModel(
            name='tbl_shop',
        ),
    ]
