# Generated by Django 4.2.4 on 2023-09-18 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_tbl_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_reply',
        ),
    ]
