# Generated by Django 4.2.4 on 2023-09-06 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_products',
        ),
    ]
