# Generated by Django 4.2.4 on 2023-09-13 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_tbl_shop_tbl_newuser'),
        ('User', '0002_tbl_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_content', models.CharField(max_length=40)),
                ('feedback_date', models.CharField(max_length=35)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_shop')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_newuser')),
            ],
        ),
    ]
