# Generated by Django 4.2.4 on 2023-09-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_tbl_feedback_shop_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_feedback',
            name='feedback_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
