# Generated by Django 4.1.1 on 2023-09-14 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_tbl_shop_tbl_newuser'),
        ('User', '0005_alter_tbl_feedback_feedback_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_newuser')),
            ],
        ),
    ]
