# Generated by Django 4.2.4 on 2023-09-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
