# Generated by Django 4.2.4 on 2023-09-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_tbl_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='status',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
