# Generated by Django 4.2.4 on 2023-09-19 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_tbl_complaint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cart',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='tbl_cart',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='tbl_booking',
        ),
        migrations.DeleteModel(
            name='tbl_cart',
        ),
    ]
