# Generated by Django 4.2.4 on 2023-09-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_tbl_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_cart',
        ),
    ]
