# Generated by Django 4.2.4 on 2023-10-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_tbl_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rating',
        ),
    ]
