# Generated by Django 4.2.4 on 2023-10-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0026_remove_tbl_rating_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='booking_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
