# Generated by Django 4.2.4 on 2023-10-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0027_tbl_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cart',
            name='status',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
